services:
  cervezario-app:
    image: kmreyes/cervezarionacional:0.0.1
    working_dir: /usr/src/app
    env_file:
      - .env.develop
    volumes:
      - ./:/usr/src/app
    ports:
      - "4500:4500"
    command: "npm run start:dev"
  db:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: clave123
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "4501:3306"
