services:
  cervezario-app:
    image: node:${NODE_VERSION}
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - "4500:${NESTJS_PORT}"
    command: "npm run start:dev"
  db:
    image: mysql:${DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_DATABASE: ${DB_NAME} 
    volumes:
      - ./db/script-creacion/creacion-db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/script-creacion/datos.sql:/docker-entrypoint-initdb.d/2.sql
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "4501:${DB_PORT}"
