services:
  cervezario-app:
    image: node:${NODE_VERSION}
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - "4500:${NESTJS_PORT}"
    command: "npm run start:dev"
    depends_on: 
      - db
  db:
    image: mysql:${DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_DATABASE: ${DB_NAME} 
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "4501:${DB_PORT}"
    platform: linux/amd64
  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./db/script-creacion:/flyway/sql
    command: -url=jdbc:mysql://db:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true -user=${DB_USER} -password=${DB_PASS_ROOT} -connectRetries=60 migrate
    depends_on: 
      db:
        condition: service_started
