services:
  cervezario-app-prod:
    image: kmreyes/cervezarionacional:0.0.1
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    command: "npm run start:prod"
  db:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: claveprod123
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "3001:3306"