services:
  cervezario-app-prod:
    image: kmreyes/cervezarionacional:1.0.1
    env_file:
      - .env
    ports:
      - "3000:${PORT}"
    command: "npm run start:prod"
  db:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: clave123
    volumes:
      - ./db/data_prod:/var/lib/mysql
    ports:
      - "3001:3306"